### ISSUE TITLE
Fatal problem in your code.

### ISSUE THREAD

**Issue by Lynkzhang** [eeric/pytorch-LBCNN#1]
your weight.requires_grad need to be after this line.
https://github.com/eeric/pytorch-LBCNN/blob/7515ee8dd9c90695ae0e3e3836d7b9ad9c974454/LBCNN.py#L20

Or Parameter() will overwritten the flag False by True(default value for parameter.)

I have do plenty of test, if you don't change the order, the LBCNN is just a normal 2DConv.

**Comment by eeric** [comment]
ok, thanks a lot!

**Comment by eeric** [comment]
@Lynkzhang 
LBCNN.py modified, was it right?

**Comment by Lynkzhang** [comment]
Yes, that is exactly what I mean~

**Comment by eeric** [comment]
@Lynkzhang, ok!
